config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'locations#home'

  resources :locations, only: [:index, :show]

  get "/map", to: "locations#index"
  get "/report", to: "locations#report"
  get "/timeline", to: "locations#timeline"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    year = params[:year]
    @locations = if year.nil?
                  Location.where("is_2017", true)
                 else
                   Location.where("is_#{year} = ?", true)
                 end
  end

  def show
    @location = Location.find(params[:id])
    @locations = Location.where(latitude: @location.latitude, longitude: @location.longitude, name: @location.name)

  end

  def home
    api_key = 'cc38c00429dc4dee93ba2451d77f9ae5'
    client = NewsService::Client.new(api_key)
    result = client.fetch_pogo_news
    @news = result[:data]['articles'] if result[:status] == 'Success'
    @error_message = result[:data] unless result[:status] == 'Success'
  end

  def report
  end

  def timeline
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MappingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'style', media: 'all' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin=""/>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    

  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/locations/_home_footer.html.erb
<footer class="bg-slate-900">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
          <div class="mb-6 md:mb-0">
              <a href="#" class="flex items-center">
                  <img src="https://i.postimg.cc/Kjt1yfYp/vp-logo.png" class="h-12 me-3" alt="V&P Logo" />
                  <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
                    <span class="text-rose-600 text-3xl">P</span>robe
                    <span class="text-rose-600 text-3xl">O</span>n
                    <span class="text-rose-600 text-3xl">G</span>uo's
                    <span class="text-rose-600 text-3xl">O</span>peration
                </span>
              </a>
          </div>
          <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Resources</h2>
                  <ul class="text-gray-500 dark:text-gray-400 font-medium">
                      <li class="mb-4">
                          <a href="https://www.pagcor.ph/index.php" class="hover:underline">PAGCOR</a>
                      </li>
                      <li>
                          <a href="https://leafletjs.com/" class="hover:underline">LeafletJS</a>
                      </li>
                  </ul>
              </div>
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Check Code</h2>
                  <ul class="text-gray-500 dark:text-gray-400 font-medium">
                      <li class="mb-4">
                          <a href="https://github.com/redroboto" class="hover:underline ">Vince's Github</a>
                      </li>
                      <li>
                          <a href="https://github.com/rootaccess2023" class="hover:underline">Paulo's Github
                          </a>
                      </li>
                  </ul>
              </div>
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Connect with us</h2>
                  <ul class="text-gray-500 dark:text-gray-400 font-medium">
                      <li class="mb-4">
                          <a href="#" class="hover:underline">Vince's LinkedIn</a>
                      </li>
                      <li>
                          <a href="https://www.linkedin.com/in/ppoliver1996/" class="hover:underline">Paulo's LinkedIn</a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
      <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
      <div class="sm:flex sm:items-center sm:justify-between">
          <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="https://flowbite.com/" class="hover:underline">V&P™</a>. All Rights Reserved.
          </span>
          <div class="flex mt-4 sm:justify-center sm:mt-0">
              <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 8 19">
                        <path fill-rule="evenodd" d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z" clip-rule="evenodd"/>
                    </svg>
                  <span class="sr-only">Facebook page</span>
              </a>
              <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 21 16">
                        <path d="M16.942 1.556a16.3 16.3 0 0 0-4.126-1.3 12.04 12.04 0 0 0-.529 1.1 15.175 15.175 0 0 0-4.573 0 11.585 11.585 0 0 0-.535-1.1 16.274 16.274 0 0 0-4.129 1.3A17.392 17.392 0 0 0 .182 13.218a15.785 15.785 0 0 0 4.963 2.521c.41-.564.773-1.16 1.084-1.785a10.63 10.63 0 0 1-1.706-.83c.143-.106.283-.217.418-.33a11.664 11.664 0 0 0 10.118 0c.137.113.277.224.418.33-.544.328-1.116.606-1.71.832a12.52 12.52 0 0 0 1.084 1.785 16.46 16.46 0 0 0 5.064-2.595 17.286 17.286 0 0 0-2.973-11.59ZM6.678 10.813a1.941 1.941 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.919 1.919 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Zm6.644 0a1.94 1.94 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.918 1.918 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Z"/>
                    </svg>
                  <span class="sr-only">Discord community</span>
              </a>
              <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 17">
                    <path fill-rule="evenodd" d="M20 1.892a8.178 8.178 0 0 1-2.355.635 4.074 4.074 0 0 0 1.8-2.235 8.344 8.344 0 0 1-2.605.98A4.13 4.13 0 0 0 13.85 0a4.068 4.068 0 0 0-4.1 4.038 4 4 0 0 0 .105.919A11.705 11.705 0 0 1 1.4.734a4.006 4.006 0 0 0 1.268 5.392 4.165 4.165 0 0 1-1.859-.5v.05A4.057 4.057 0 0 0 4.1 9.635a4.19 4.19 0 0 1-1.856.07 4.108 4.108 0 0 0 3.831 2.807A8.36 8.36 0 0 1 0 14.184 11.732 11.732 0 0 0 6.291 16 11.502 11.502 0 0 0 17.964 4.5c0-.177 0-.35-.012-.523A8.143 8.143 0 0 0 20 1.892Z" clip-rule="evenodd"/>
                </svg>
                  <span class="sr-only">Twitter page</span>
              </a>
              <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M10 .333A9.911 9.911 0 0 0 6.866 19.65c.5.092.678-.215.678-.477 0-.237-.01-1.017-.014-1.845-2.757.6-3.338-1.169-3.338-1.169a2.627 2.627 0 0 0-1.1-1.451c-.9-.615.07-.6.07-.6a2.084 2.084 0 0 1 1.518 1.021 2.11 2.11 0 0 0 2.884.823c.044-.503.268-.973.63-1.325-2.2-.25-4.516-1.1-4.516-4.9A3.832 3.832 0 0 1 4.7 7.068a3.56 3.56 0 0 1 .095-2.623s.832-.266 2.726 1.016a9.409 9.409 0 0 1 4.962 0c1.89-1.282 2.717-1.016 2.717-1.016.366.83.402 1.768.1 2.623a3.827 3.827 0 0 1 1.02 2.659c0 3.807-2.319 4.644-4.525 4.889a2.366 2.366 0 0 1 .673 1.834c0 1.326-.012 2.394-.012 2.72 0 .263.18.572.681.475A9.911 9.911 0 0 0 10 .333Z" clip-rule="evenodd"/>
                  </svg>
                  <span class="sr-only">GitHub account</span>
              </a>
              <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ms-5">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 0a10 10 0 1 0 10 10A10.009 10.009 0 0 0 10 0Zm6.613 4.614a8.523 8.523 0 0 1 1.93 5.32 20.094 20.094 0 0 0-5.949-.274c-.059-.149-.122-.292-.184-.441a23.879 23.879 0 0 0-.566-1.239 11.41 11.41 0 0 0 4.769-3.366ZM8 1.707a8.821 8.821 0 0 1 2-.238 8.5 8.5 0 0 1 5.664 2.152 9.608 9.608 0 0 1-4.476 3.087A45.758 45.758 0 0 0 8 1.707ZM1.642 8.262a8.57 8.57 0 0 1 4.73-5.981A53.998 53.998 0 0 1 9.54 7.222a32.078 32.078 0 0 1-7.9 1.04h.002Zm2.01 7.46a8.51 8.51 0 0 1-2.2-5.707v-.262a31.64 31.64 0 0 0 8.777-1.219c.243.477.477.964.692 1.449-.114.032-.227.067-.336.1a13.569 13.569 0 0 0-6.942 5.636l.009.003ZM10 18.556a8.508 8.508 0 0 1-5.243-1.8 11.717 11.717 0 0 1 6.7-5.332.509.509 0 0 1 .055-.02 35.65 35.65 0 0 1 1.819 6.476 8.476 8.476 0 0 1-3.331.676Zm4.772-1.462A37.232 37.232 0 0 0 13.113 11a12.513 12.513 0 0 1 5.321.364 8.56 8.56 0 0 1-3.66 5.73h-.002Z" clip-rule="evenodd"/>
                </svg>
                  <span class="sr-only">Dribbble account</span>
              </a>
          </div>
      </div>
    </div>
</footer>

app/views/locations/_home_map.html.erb
<div class="flex flex-col justify-center gap-2 text-white md:mx-auto md:gap-4">
    <span>
        <h1 class="montserrat-semibold  w-full text-4xl transition-all ease-in-out duration-300 md:text-5xl lg:text-7xl xl:text-8xl">POGO HUBS</h1>
        <h1 class="montserrat-semibold  w-full text-4xl transition-all ease-in-out duration-300 md:text-5xl lg:text-7xl xl:text-8xl">EXPLOSION</h1>
    </span>
    <h2 class="montserrat-semibold  w-full text-3xl transition-all ease-in-out duration-300 md:text-[2rem] lg:text-4xl xl:text-6xl">The Progression of POGO Hubs</h2>
    <p class="transition-all ease-in-out duration-300 md:text-xl lg:text-2xl xl:text-3xl">Dive into the rapid growth of Philippine Offshore Gaming Operators (POGO) hubs over the past seven years. This section charts their expansion, highlighting key milestones and the factors driving their proliferation.</p>
    <%= link_to "/map" do %>
    <button class="px-4 py-2 mt-2 md:text-lg md:px-12 xl:py-4 rounded-full hover:before:bg-yellow-500 relative h-[50px] w-40 overflow-hidden border border-yellow-500 font-semibold text-yellow-300 transition-all duration-300 before:absolute before:bottom-0 before:left-0 before:top-0 before:z-0 before:h-full before:w-0 before:bg-yellow-500 before:transition-all before:duration-300 hover:text-white hover:before:left-0 hover:before:w-full flex items-center justify-center whitespace-nowrap bg-transparent">
        <span class="relative z-10">Browse Map</span>
    </button>
    <% end %>
</div>

app/views/locations/_index_details.html.erb
<div class="h-screen bg-[#fcfdfd] relative pt-8">
    <section class="bg-white px-6 pb-4 border-b">
        <form class="flex items-center max-w-full mx-auto">
            <label for="simple-search" class="sr-only">Search</label>
            <div class="relative w-full">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5v10M3 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0 10a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm12 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm0 0V6a3 3 0 0 0-3-3H9m1.5-2-2 2 2 2"/>
                    </svg>
                </div>
                <input type="text" id="simple-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  " placeholder="Search POGO" required />
            </div>
            <button type="submit" class="p-2.5 ms-2 text-sm font-medium text-white bg-blue-700 rounded-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
                <span class="sr-only">Search</span>
            </button>
        </form>
    </section>
    <section class="pb-3 w-[24.5rem]">
        <div class="bg-white">
            <ol class="no-scrollbar flex max-h-[11rem] overflow-scroll max-w-[22.5rem] mx-auto">
            <% default_year = "2017" %>
            <% current_year = params[:year] || default_year %>
            <% (2017..2024).each do |year| %>
                <% is_selected = (current_year == year.to_s) %>
                <%= link_to "/map?year=#{year}" do %>
                <li class="flex px-2 pt-2 pb-1 <%= is_selected ? 'text-blue-700 font-bold border-b-[3px] border-blue-600' : 'hover:border-b-[3px] hover:border-blue-400 text-gray-500' %>">
                    <span class="text-[0.9rem]"><%= year %></span>
                </li>
                <% end %>
            <% end %>
            </ol>

        </div>
        <div class="px-6 pt-4">
        <% case current_year %>
        <% when "2017" %>
            <%= image_tag 'https://i.postimg.cc/DwxXwtkS/manila-1.jpg', alt: 'Manila Cityscape', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">The Rise of POGO</p>
        <% when "2018" %>
            <%= image_tag 'https://i.postimg.cc/XvWbZ9XZ/pacor.png', alt: 'PAGCOR', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">Regulatory Developments</p>
        <% when "2019" %>
            <%= image_tag 'https://i.postimg.cc/VLCZSR5z/protests.png', alt: 'PAGCOR', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">Economic and Controversies</p>
        <% when "2020" %>
            <%= image_tag 'https://i.postimg.cc/VLCZSR5z/protests.png', alt: 'POGO Protest', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">The Impact of COVID-19</p>
        <% when "2021" %>
            <%= image_tag 'https://i.postimg.cc/y8bx8tY8/offices.png', alt: 'Empty POGO Offices', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">Illegal Operations</p>
        <% when "2022" %>
            <%= image_tag 'https://i.postimg.cc/4dRkxbD0/pogo.png', alt: 'PAGCOR Tax', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">Taxation and Policy</p>
        <% when "2023" %>
            <%= image_tag 'https://i.postimg.cc/xj7y7fz6/job.png', alt: 'Job Displacement due to POGO Closure', class: "h-auto rounded-lg shadow" %>
            <p class="absolute top-[19rem] left-12 text-white text-xl font-bold">Industry Decline</p>
        <% when "2024" %>
            <%= image_tag 'https://i.postimg.cc/jSTPfvmb/New-Project.png', alt: 'POGO Ban', class: "h-auto rounded-lg shadow" %>
        <% end %>
        </div>
    </section>
    <h4 class="flex items-center text-sm py-2 pl-6 gap-2">
        <svg class="size-3" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 122.88 112.5" style="enable-background:new 0 0 122.88 112.5" xml:space="preserve"><style type="text/css">.st0{fill-rule:evenodd;clip-rule:evenodd;}</style><g><path class="st0" d="M12.56,87.39c6.93,0,12.56,5.62,12.56,12.56c0,6.93-5.62,12.56-12.56,12.56C5.62,112.5,0,106.88,0,99.95 C0,93.01,5.62,87.39,12.56,87.39L12.56,87.39z M35.07,88.24h86.38c0.79,0,1.43,0.64,1.43,1.43v19.93c0,0.79-0.64,1.43-1.43,1.43 H35.07c-0.79,0-1.43-0.64-1.43-1.43V89.67C33.64,88.88,34.29,88.24,35.07,88.24L35.07,88.24z M35.07,44.7h86.38 c0.79,0,1.43,0.64,1.43,1.43v19.93c0,0.79-0.64,1.43-1.43,1.43H35.07c-0.79,0-1.43-0.64-1.43-1.43V46.13 C33.64,45.34,34.29,44.7,35.07,44.7L35.07,44.7z M35.07,1.16h86.38c0.79,0,1.43,0.64,1.43,1.43v19.93c0,0.79-0.64,1.43-1.43,1.43 H35.07c-0.79,0-1.43-0.64-1.43-1.43V2.59C33.64,1.8,34.29,1.16,35.07,1.16L35.07,1.16z M12.56,43.69c6.93,0,12.56,5.62,12.56,12.56 c0,6.93-5.62,12.56-12.56,12.56C5.62,68.81,0,63.19,0,56.25C0,49.32,5.62,43.69,12.56,43.69L12.56,43.69z M12.56,0 c6.93,0,12.56,5.62,12.56,12.56c0,6.93-5.62,12.56-12.56,12.56C5.62,25.11,0,19.49,0,12.56C0,5.62,5.62,0,12.56,0L12.56,0z"/></g></svg>
        <span class="font-bold">List of POGO Hubs</span>
    </h4>
    <section class="pl-6 pr-3">
        <% if @locations.present? %>
            <ul class="custom-height overflow-scroll">
                <% @locations.each do |location| %>
                    <%= link_to location_path(location), class: "flex mr-3 group border-b-[1px] border-zinc-100 bg-white" do %>
                        <div class="transition-all duration-4000ms w-[5px] bg-blue-500 opacity-0 invisible group-hover:opacity-100 group-hover:visible"></div>                        <div class="w-full flex flex-col p-4 group-hover:bg-[#eff5f7] ">
                            <h1 class="text-slate-600 tracking-tighter pb-1"><%= location.name %></h1>
                            <p class="text-[0.65rem] bg-[#dde3f6] w-fit text-blue-700 px-2 py-1 rounded font-semibold">GAMBLING HOUSE</p>
                        </div>
                        <div class="flex items-center pr-4 group-hover:bg-[#eff5f7] ">
                            <svg class="size-6 fill-neutral-400 group-hover:fill-blue-600" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="122.883px" height="122.882px" viewBox="0 0 122.883 122.882" enable-background="new 0 0 122.883 122.882" xml:space="preserve"><g><path d="M61.441,0C44.475,0,29.115,6.877,17.996,17.996C6.877,29.115,0,44.475,0,61.441c0,16.966,6.877,32.326,17.996,43.445 c11.119,11.118,26.479,17.995,43.445,17.995c16.967,0,32.327-6.877,43.446-17.995c11.119-11.119,17.996-26.479,17.996-43.445 c0-16.967-6.877-32.327-17.996-43.445C93.768,6.877,78.408,0,61.441,0L61.441,0z M51.505,42.166 c-1.735-1.784-1.696-4.637,0.088-6.372c1.784-1.735,4.637-1.696,6.373,0.088l21.839,22.521l-3.23,3.142l3.244-3.146 c1.738,1.792,1.693,4.652-0.098,6.39c-0.053,0.05-0.105,0.099-0.158,0.146L57.966,87.017c-1.735,1.784-4.588,1.823-6.373,0.088 c-1.784-1.734-1.823-4.588-0.088-6.372l18.78-19.201L51.505,42.166L51.505,42.166z M24.386,24.386 C33.869,14.903,46.97,9.038,61.441,9.038c14.471,0,27.573,5.865,37.055,15.348c9.484,9.483,15.35,22.584,15.35,37.056 c0,14.471-5.865,27.572-15.35,37.055c-9.482,9.483-22.584,15.349-37.055,15.349c-14.471,0-27.572-5.865-37.055-15.349 C14.903,89.014,9.038,75.912,9.038,61.441C9.038,46.97,14.903,33.869,24.386,24.386L24.386,24.386z"/></g></svg>
                        </div>
                    <% end %>
                <% end %>
            </ul>
        <% else %>
            <p class="text-sm text-justify pr-3">There is no available data from the Philippine Amusement and Gaming Corporation (PAGCOR) regarding Philippine Offshore Gaming Operators (POGOs) due to the disruptions caused by the COVID-19 pandemic. The pandemic led to operational challenges and data collection issues, resulting in a lack of comprehensive information for that year.</p>
        <% end %>
    </section>
</div>

app/views/locations/_index_dropdown.html.erb
<div class="relative flex flex-col justify-center items-center">
  <button class="w-full flex flex-col items-center justify-center text-white text-xs rounded md:hidden" data-action="click->dropdown#toggle">
    <svg class="flex justify-center size-6 hover:scale-110 transition duration-300 fill-white md:hidden" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="122.88px" height="107.128px" viewBox="0 0 122.88 107.128" enable-background="new 0 0 122.88 107.128" xml:space="preserve"><g><path d="M2.788,0h117.297c1.544,0,2.795,1.251,2.795,2.795c0,0.85-0.379,1.611-0.978,2.124l-46.82,46.586v39.979 c0,1.107-0.643,2.063-1.576,2.516l-22.086,12.752c-1.333,0.771-3.039,0.316-3.812-1.016c-0.255-0.441-0.376-0.922-0.375-1.398 h-0.006V51.496L0.811,4.761C-0.275,3.669-0.27,1.904,0.822,0.819c0.544-0.541,1.255-0.811,1.966-0.811V0L2.788,0z M113.323,5.591 H9.493L51.851,48.24c0.592,0.512,0.966,1.27,0.966,2.114v49.149l16.674-9.625V50.354h0.008c0-0.716,0.274-1.432,0.822-1.977 L113.323,5.591L113.323,5.591z"/></g></svg>
    Details
</button>
  <div data-dropdown-target="list" class="hidden z-10 bg-gray-800">
    <ol class="absolute z-1000">
        <%= link_to "/map?year=2017" do %>
            <li>2017</li>
        <% end %>
        <%= link_to "/map?year=2018" do %>
            <li>2018</li>
        <% end %>
        <%= link_to "/map?year=2019" do %>
            <li>2019</li>
        <% end %>
        <%= link_to "/map?year=2020" do %>
            <li>2020</li>
        <% end %>
        <%= link_to "/map?year=2021" do %>
            <li>2021</li>
        <% end %>
        <%= link_to "/map?year=2022" do %>
            <li>2022</li>
        <% end %>
        <%= link_to "/map?year=2023" do %>
            <li>2023</li>
        <% end %>
        <%= link_to "/map?year=2024" do %>
            <li>2024</li>
        <% end %>
    </ol>
  </div>
</div>

app/views/locations/_map.html.erb
<div class="h-full" data-controller="map" data-map-latlong-value="<%=locations.pluck(:latitude, :longitude, :name, :address)%>">
    <div data-map-target="container" class="h-full w-full relative -z-1"></div>
</div>

app/views/locations/_show_license.html.erb
<% years_with_comma = [] %>
<% (2017..2024).each do |year| %>
    <% if @location.send("is_#{year}") %>
        <% years_with_comma << year %>
    <% end %>
<% end %>
<%= years_with_comma.join(', ') %>

app/views/locations/_show_map.html.erb
<div class="h-full" data-controller="map" data-map-latlong-value="<%=locations.pluck(:latitude, :longitude, :name, :address)%>">
    <div data-map-target="container" class="h-full w-full relative -z-1"></div>
</div>

app/views/locations/_show_operation.html.erb
<% count_of_years = 0 %>
<% (2017..2024).each do |year| %>
    <% if @location.send("is_#{year}") %>
        <% count_of_years += 1 %>
    <% end %>
<% end %>
<%= count_of_years %>

app/views/locations/report.html.erb
<h1>This is the report page</h1>